services:
  pulseguard:
    image: pulseguard
    build:
      context: .
      dockerfile: PulseGuard/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__PulseStore=${PULSESTORE_CONNECTION_STRING}
